name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy scikit-learn
    - name: Install citrine_challenge
      run: |
        python setup.py develop --user
    - name: Test with unit2
      run: |
        pip install unittest2
        unit2 discover test/citrine_challenge/
